name: soggetto-cavato
version: !include "./VERSION"
synopsis: Carve music from words.
description: See README at <https://github.com/yurrriq/soggetto-cavato#readme>
maintainer: Eric Bailey <eric@ericb.me>
license: BSD3
github: yurrriq/soggetto-cavato
category: Text
extra-source-files:
- CHANGELOG.md

ghc-options: -Wall

dependencies:
- base

library:
  source-dirs: src
  exposed-modules:
  - Text.SoggettoCavato
  dependencies:
  - Euterpea

executables:
  sc:
    main: Main.hs
    source-dirs: app
    dependencies:
    - soggetto-cavato
