resolver: lts-8.5
extra-deps:
  - Euterpea-2.0.2
  - PortMidi-0.1.5.2
  - Stream-0.4.7.2
  - arrows-0.4.4.1
  - heap-0.6.0
  - lazysmallcheck-0.6
  - stm-2.4.2
nix:
  enable: true
  shell-file: shell.nix
system-ghc: true
